# fly.toml file generated for api-heatmap-farcapital on 2023-01-28T17:54:45+07:00

app = "api-heatmap-farcapital"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  DB_CONNECTION = "pgsql"
  DB_HOST = "top2.nearest.of.farcapdb.internal"
  DB_DATABASE= "api_heatmap_farcapital"
  OPENTRIPMAP_TOKEN="5ae2e3f221c38a28845f05b601f63e17be02115427b01e17561f8434"
  FSQ_TOKEN="fsq30FGrY4U/Nq7CtL31j/icKlyXPoAZbIa9pVnCHNNg/B4="

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
